# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The box is optional in newer versions of Vagrant
  # config.vm.box = "dummy"

  config.vm.provider :rackspace do |rs|
    rs.username = "REPLACE_THIS"
    rs.api_key  = "REPLACE_THIS"
    rs.flavor   = /1 GB Performance/
    rs.image    = /Ubuntu/
#    rs.ssh.private_key_path = '~/.ssh/REPLACE_THIS.pem'
    rs.rackspace_region = :iad
    rs.public_key_path = '~/.ssh/REPLACE_THIS.pem.pub'
    rs.metadata = {"key" => "value"}       # optional
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
  end

end
