# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    override.ssh.pty = true
    override.ssh.username = "ubuntu"
    aws.access_key_id = "REPLACE_THIS"
    aws.secret_access_key = "REPLACE_THIS"
    aws.ami = "ami-5189a661"
    aws.keypair_name = "REPLACE_THIS"
    override.ssh.private_key_path = "~/.ssh/REPLACE_THIS.pem"
    aws.instance_type = "t2.micro"
    aws.subnet_id = "REPLACE_THIS"
    aws.associate_public_ip = true
    aws.security_groups = "REPLACE_THIS"
    aws.region = "us-west-2"
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
  end

end
