# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  #config.vm.provision "shell", path: "https://gist.githubusercontent.com/lvnilesh/6450616/raw/4b37bfb9eb6833826905861195db77bc29d9335c/vagrant-lamp.sh"
  #config.vm.provision "shell", path: "https://gist.githubusercontent.com/lvnilesh/2c5e1a0175ac6f7c849a/raw/e11545bc5cc4280f0616bdc4d1d1be3a1cbf4998/dbsetup.sh"

  #config.vm.provision "ansible" do |ansible|
  #    ansible.playbook = "playbook.yml"
  #end

end
