Vagrant.configure('2') do |config|
  config.vm.hostname = 'dropletname.example.com'
  config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/vagrant_digitalocean'
            override.vm.box = 'digital_ocean'
                override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

                    provider.token = ENV['DIGITALOCEAN']
                        provider.image = 'ubuntu-14-04-x64'
                            provider.region = 'nyc2'
                                provider.size = '512mb'
                                  end
end
